### ISSUE TITLE
Updating a "GoalUser"

### ISSUE THREAD

**Issue by eladex** [rabiran/Kartoffel#149]
when trying to update a person with `entityType=GoalUser` we get an error 
`"entityType: GoalUser requires at least 1 domainuser"`
this happens because we delete the domainUsers array before updating.
(inside `updatePerson` function)
maybe solvable if we delete the array from `change` parameter instead from `mergedPerson`

https://github.com/rabiran/Kartoffel/blob/84557e4634224c0d715f20bd2fcc3c8699b1ce47/src/person/person.controller.ts#L233-L239

**Comment by GrishaDev** [comment]
what if we remove this line:
`delete mergedPerson.domainUsers;`

but not allow "domainUsers" field to come in change object?
`export const updateAllowedFields = _.without(createAllowedFileds, 'directGroup', 'identityCard', 'personalNumber', 'domainUsers');`

there is no reason to be able to update domainUsers field via person PUT, since there is a route to update domainUsers

**Comment by eladex** [comment]
It is a good idea in general to validate before the controller; however, this fix will require a lot of fixes in the tests - because a lot of them doing something like this:
1. get an object
2. add / change a field
3. send back the object to the `updatePerson()` function.

the object sent in step 3 will sometimes have a `domainUsers` field.

In addition to your fix, it is possible to define new types for person update (that will include only the updatable fields) and person create.
 e.g:
`type PersonUpdate = Partial<Omit<IPerson, 'identityCard' | 'personalNumber' | 'domainUsers' | 'hierarchy' | 'updatedAt' |
'createdAt'>>
`

**Comment by GrishaDev** [comment]
It looks alright on tests from first look, they dont seem to send `domainUsers `field to `updatePerson()`.
even if yes, its not a problem to update the domainUsers with the update domain function in tests.

**Comment by eladex** [comment]
I think that there are several tests that "bypass" the suggested fix (they just call `updatePerson()` directly)
https://github.com/rabiran/Kartoffel/blob/f5de4c2f30d9d151d44ec0828478f7a37cf9d3c7/src/person/person.spec.ts#L598-L607
The `person` object that sent as `change` parameter will have `domainUsers` field

**Comment by GrishaDev** [comment]
oh yes, then can simply send a seperate object to update in tests:

```
   let person = await Person.createPerson(<IPerson>{ ...personExamples[0] }); 
   await Person.addNewUser(person.id, newUserExample); 
   const updateObject = {};
   updateObject.job = 'Programmer'; 
   updateObject.rank = RANK[0]; 
   updateObject.responsibility = RESPONSIBILITY[1]; 
   updateObject.responsibilityLocation = new Types.ObjectId(dbIdExample[0]); 
  
   const updatedPerson = await Person.updatePerson(person.id, updateObject); 
```

**Comment by eladex** [comment]
yep,
the issue fixer should also fix all these tests
